version: "3.7"
services:
  mysqldb:
    image: mysql:8.0.16
    environment:
      MYSQL_ROOT_PASSWORD: todo_tasks
      MYSQL_DATABASE: todo_tasks
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    networks:
      - mynw
  todo:
    depends_on:
      - mysqldb
    build: .
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    command: npm start
    environment:
      PORT: 3000
    networks:
      - mynw
    tty: true
volumes:
  dbdata:
networks:
  mynw:
    driver: bridge
